version: '3.8'
services:
  # Jira
  jira:
    image: atlassian/jira-software:9.0.0
    ports:
      - "8080:8080"
    volumes:
      - jira_data:/var/atlassian/application-data/jira
    environment:
      - ATL_PROXY_NAME=10.77.150.23
      - ATL_PROXY_PORT=8080
    restart: unless-stopped

  # PostgreSQL (слушаем на всех интерфейсах)
  confluence-db:
    image: postgres:13
    environment:
      POSTGRES_DB: confluence
      POSTGRES_USER: confluence
      POSTGRES_PASSWORD: confluence123
    ports:
      - "5432:5432"  # Пробрасываем порт на хост
    volumes:
      - confluence_db_data:/var/lib/postgresql/data
    command: >
      postgres 
      -c listen_addresses='*' 
      -c max_connections=200 
      -c shared_preload_libraries=pg_stat_statements 
      -c pg_stat_statements.track=all
    restart: unless-stopped

  # Confluence
  confluence:
    image: atlassian/confluence:8.5.0
    depends_on:
      - confluence-db
    ports:
      - "8090:8090"
    volumes:
      - confluence_data:/var/atlassian/application-data/confluence
    environment:
      - ATL_DB_TYPE=postgresql
      - ATL_JDBC_URL=jdbc:postgresql://10.77.150.23:5432/confluence
      - ATL_JDBC_USER=confluence
      - ATL_JDBC_PASSWORD=confluence123
      - ATL_PROXY_NAME=10.77.150.23
      - ATL_PROXY_PORT=8090
    restart: unless-stopped

volumes:
  jira_data:
  confluence_data:
  confluence_db_data:
